### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by ayadenchu** [ayadenchu/furima-31065#11]
本番環境URL
https://furima-31065.herokuapp.com/
Basic認証のIDとパスワード
ユーザー名：admin　パスワード：2222

出品者用
メールアドレス：aaaaa@com
パスワード：1111aaaa
購入者用
メールアドレス：bbbbb@com
パスワード：2222bbbb

カード番号 | 4242424242424242（16桁）
CVC | 123
有効期限 | 登録時より未来

**Comment by mo1015** [comment]
田中さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
**○商品詳細画面で、「商品説明」が表示されるようにしましょう
○商品編集で適切では無い値が入力された場合、エラーメッセージを出力させるようにしましょう**

修正でき次第、以下の最終課題完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by naru6117** [comment]
ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！


**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**
